# Generated by Django 5.0.12 on 2025-02-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=100, unique=True)),
                ('membership_category', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10)),
                ('membership_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('no_of_days', models.IntegerField(help_text='Number of days for this membership')),
                ('membership_limit', models.CharField(choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=10)),
                ('membership_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('select_class', models.CharField(help_text='Class type or category', max_length=100)),
                ('installment_plan', models.BooleanField(default=False, help_text='Is installment available?')),
                ('signup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('membership_description', models.TextField(blank=True, help_text='Optional membership details')),
                ('membership_image', models.ImageField(blank=True, null=True, upload_to='membership/images/')),
            ],
        ),
    ]
