# Generated by Django 5.0.12 on 2025-02-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=255)),
                ('starting_year', models.IntegerField()),
                ('gym_address', models.TextField()),
                ('office_phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('system_language', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gym_logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('height_unit', models.CharField(default='cm', max_length=10)),
                ('chest_unit', models.CharField(default='cm', max_length=10)),
                ('waist_unit', models.CharField(default='cm', max_length=10)),
                ('arms_unit', models.CharField(default='cm', max_length=10)),
                ('fat_unit', models.CharField(default='%', max_length=10)),
                ('members_can_view_others', models.BooleanField(default=False)),
                ('staff_can_view_trainees', models.BooleanField(default=False)),
                ('enable_alert_email', models.BooleanField(default=False)),
                ('reminder_before_days', models.IntegerField(blank=True, null=True)),
                ('reminder_message', models.TextField(blank=True, null=True)),
                ('members_can_message_each_other', models.BooleanField(default=False)),
                ('left_header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
